#ifndef __COMM_H_
#define __COMM_H_

#define INNER_DISPLAY_ID	0
#define OUTER_DISPLAY_ID	1

#define THIS_ID		INNER_DISPLAY_ID

enum COMMAND
{
	INNER_DISPLAY_ON_CMD = 2,
	INNER_DISPLAY_OFF_CMD,
	OUTER_DISPLAY_ON_CMD,
	OUTER_DISPLAY_OFF_CMD,
	
	INNER_ROTATION_CW_START_CMD,
	INNER_ROTATION_STOP_CMD,
	OUTER_ROTATION_CW_START_CMD,
	OUTER_ROTATION_CCW_START_CMD,
	OUTER_ROTATION_STOP_CMD,

	MUSIC_START_CMD,
	MUSIC_STOP_CMD,
	
	STRING_RECEIVE_CMD,
	IMG_RECEIVE_CMD,
};

void init_Comm(void);

__inline void detect_RX_Data(void);

#endif